version: '3.7'
services:
  mongo-db-study-project:
    container_name: mongodbStudyProject
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'rootpassword'
    ports:
      - 27019:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
